### ISSUE TITLE
Link https://qcobjects.dev/ off

### ISSUE THREAD

**Issue by Iyov** [QuickCorp/QCObjects#4]
When I try to load the website https://qcobjects.dev/ I get an error, I can not enter.
I tried to ping and it does not give me good results.
Please fix it.
Thank you!
FB
![65614886_633791150436400_8293430356489535488_n](https://user-images.githubusercontent.com/50718004/60683429-aa721700-9e65-11e9-8323-270f67bdea89.png)

**Comment by jeanmachuca** [comment]
Ok, for some reason DNS CNAME record of  github pages wasn’t propagating to all networks. So that problem was solved adding an A record pointing to the every IP of GitHub pages as additional task to adding the cname record.

The IPs added to DNS as A record were:

A @ to 185.199.108.153
A @ to 185.199.109.153
A @ to 185.199.110.153
A @ to 185.199.111.153

As a result, now the domain is pointing by cname redirect to the project of organisation and also it is pointing straight to the github pages set of ip.

If you still got any trouble feel free to reopen this issue. Thanks
