### ISSUE TITLE
SwaggerUI Example Doesn't Work when container is a shadowed component

### ISSUE THREAD

**Issue by topcheese** [QuickCorp/QCObjects#80]
**Describe the bug**
SwaggerUI doesn't show, but only returns the following error in the console.

**To Reproduce**

Complete the example provided.
**Expected behavior**
Expected it to show like in example image.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS 10.14
 - Chrome
 - Version 92.0.4515.107

**Additional context**
localhost/:1 This site does not have a valid SSL certificate! Without SSL, your site's and visitors' data is vulnerable to theft and tampering. Get a valid SSL certificate before releasing your website to the public.
An SSL certificate error occurred when fetching the script.
react-dom.production.min.js:296 Uncaught Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.t.render (react-dom.production.min.js:296)
    at fe (root-injects.jsx:69)
    at m (index.js:192)
    at Yr (index.js:213)
    at QCObjects.startSwaggerUI (org.qcobjects.controllers.swagger.js:35)
    at QCObjects.done (org.qcobjects.controllers.swagger.js:70)
    at HTMLScriptElement.document.getElementsByTagName.appendChild.s.onload (QCObjects.js:3475)
t.render @ react-dom.production.min.js:296
fe @ root-injects.jsx:69
m @ index.js:192
Yr @ index.js:213
startSwaggerUI @ org.qcobjects.controllers.swagger.js:35
done @ org.qcobjects.controllers.swagger.js:70
document.getElementsByTagName.appendChild.s.onload @ QCObjects.js:3475
load (async)
(anonymous) @ QCObjects.js:3473
rebuild @ QCObjects.js:3483
_new_ @ QCObjects.js:3496
New @ QCObjects.js:958
done @ org.qcobjects.controllers.swagger.js:66
componentDone @ QCObjects.js:3083
(anonymous) @ QCObjects.js:2478
Promise.then (async)
_componentLoaderInBrowser @ QCObjects.js:2475
componentLoader @ QCObjects.js:2584
(anonymous) @ QCObjects.js:1737
rebuild @ QCObjects.js:1730
_new_ @ QCObjects.js:2051
New @ QCObjects.js:958
__create_component_instance_ @ QCObjects.js:3201
(anonymous) @ QCObjects.js:3235
_buildComponent @ QCObjects.js:3051
componentDone @ QCObjects.js:3100
(anonymous) @ QCObjects.js:2478
Promise.then (async)
_componentLoaderInBrowser @ QCObjects.js:2475
componentLoader @ QCObjects.js:2584
(anonymous) @ QCObjects.js:1737
rebuild @ QCObjects.js:1730
_new_ @ QCObjects.js:2051
New @ QCObjects.js:958
__create_component_instance_ @ QCObjects.js:3201
(anonymous) @ QCObjects.js:3235
_buildComponent @ QCObjects.js:3051
componentDone @ QCObjects.js:3100
(anonymous) @ QCObjects.js:2478
Promise.then (async)
_componentLoaderInBrowser @ QCObjects.js:2475
componentLoader @ QCObjects.js:2584
(anonymous) @ QCObjects.js:1737
rebuild @ QCObjects.js:1730
_new_ @ QCObjects.js:2051
New @ QCObjects.js:958
__create_component_instance_ @ QCObjects.js:3201
(anonymous) @ QCObjects.js:3235
_buildComponent @ QCObjects.js:3051
componentDone @ QCObjects.js:3100
(anonymous) @ QCObjects.js:2478
Promise.then (async)
_componentLoaderInBrowser @ QCObjects.js:2475
componentLoader @ QCObjects.js:2584
(anonymous) @ QCObjects.js:1737
rebuild @ QCObjects.js:1730
_reroute_ @ QCObjects.js:2075
_new_ @ QCObjects.js:2050
New @ QCObjects.js:958
__create_component_instance_ @ QCObjects.js:3201
(anonymous) @ QCObjects.js:3235
_buildComponent @ QCObjects.js:3051
componentDone @ QCObjects.js:3098
(anonymous) @ QCObjects.js:2478
Promise.then (async)
_componentLoaderInBrowser @ QCObjects.js:2475
componentLoader @ QCObjects.js:2584
(anonymous) @ QCObjects.js:1737
rebuild @ QCObjects.js:1730
_new_ @ QCObjects.js:2051
New @ QCObjects.js:958
__create_component_instance_ @ QCObjects.js:3201
(anonymous) @ QCObjects.js:3235
_buildComponent @ QCObjects.js:3051
Element.buildComponents @ QCObjects.js:3242
_buildComponents @ QCObjects.js:2891
__start__ @ QCObjects.js:2904
(anonymous) @ QCObjects-SDK.js:84
Promise.then (async)
(anonymous) @ QCObjects-SDK.js:80
(anonymous) @ QCObjects-SDK.js:89

**Comment by jeanmachuca** [comment]
Thank you for test and report this bug.

I've changed the title of this issue to "SwaggerUI Example Doesn't Work when container is a shadowed component" as it can be reproduced with the latest version of the default app template used by the CLI to create the app in the example.

So one more step should be added to the tutorial to keep the example running. In lines 18-19 of index.html, the shadowed attribute of component layout-basic, needs to be changed to false in order to allow Swagger UI to inject the code into the DOM. 

```html
  <component name="layout-basic" shadowed=true cached=true controllerClass="MainController">
  </component>
```


Explanation of the problem:

[Shadowed Components](https://hackernoon.com/shadowed-components-and-qcobjects-kd703yld) is a special feature of QCObjects that implements the feature Shadow DOM supported by the modern browsers (for more information read about the [Shadow Root official spec](https://dom.spec.whatwg.org/#shadowroot) ). One powerful benefit of using Shadow DOM is that the internal DOM of a component can be isolated from the rest of the DOM tree, and when the shadow mode is closed, the DOM subtree can't be even inspectable. This is so useful most of the times and also improves performance in rendering processes as the browser renders the shadow root in separated threads. 

This time, the component layout-basic was declared in the index.html as shadowed=true, that means everything into the body will be converted to a shadow root. The body of the component will be not accessible in a direct way (to access the body of a shadowed component you should do it by accessing the shadowHost element, read more about [Shadowed Components of QCObjects here](https://hackernoon.com/shadowed-components-and-qcobjects-kd703yld) ) . For that reason the [SwaggerUIController](https://github.com/QuickCorp/QCObjects-SDK/blob/master/js/org.qcobjects.controllers.swagger.js) is not able to be accessing the DOM of its component, as this component is inside the Shadow DOM of the layout-basic component that is the main component of the document.

Solution:

So when you declare layout-basic with the attribute shadowed=false or remove the attribute from the tag declaration, you are disabling the Shadowed component behaviour and using the layout-basic as a Lighting Component. This change will not affect the example and will enable SwaggerUI to access the DOM. In future versions of the [QCObjects SDK](http://sdk.qcobjects.dev/), there will be a way to dynamically detect when a shadowed component is being used in a parent scope.



```html
  <component name="layout-basic" shadowed=false ...>
  </component>
```

Change shadowed attribute to false and then restart the server.

If you have more problems related with this issue, please re-open it and comment your details.

**Comment by topcheese** [comment]
I'm not seeing the same thing for "layout-basic" in index.html.  I do see a layout-basic tag on line 20 that is shadowed, and changing it to false fixes the problem.
  I'm having trouble finding the component declaration for layout-basic, as you have it written.
I know it's got to be there somewhere.  I'll play around with it some more.

**Comment by jeanmachuca** [comment]
Good, I'm sorry, my fault as I was explaining the code of an older version of the default app template. The code of the [version 1.2.77 of the app template](https://github.com/QuickCorp/qcobjects-new-app/releases/tag/v1.2.77) that is what I was talking about is [here](https://github.com/QuickCorp/qcobjects-new-app/releases/tag/v1.2.77) 

In the latest version of [QCObjects New App Template](https://www.npmjs.com/package/qcobjectsnewapp) it is being implemented the use of Smart Widgets, that is a new feature to add some sugar to the classic component tag syntax. 

If you see into the code of the app template in the line 56 of the file [init.js](https://github.com/QuickCorp/qcobjects-new-app/blob/master/js/init.js) of the newest version,  you can find this:

```javascript
RegisterWidgets("layout-basic", "splash-screen");
```

This is telling QCObjects to interpret a <layout-basic> and <splash-screen> custom element declaration as a Smart Widget that implements a component inside, basically to allow you to use an even more fancy way to declare a component. A smart widget is actually using the same attributes than a component declaration, and in practice, it is creating a component declaration dynamically into its DOM. So most of the times you will find useful to summarise this:

```javascript
<component name="layout-basic"  ...></component>
```

into this:

```javascript
<layout-basic ...></layout-basic>
```

NOTE: For Smart Widgets, the name of the custom element tag must to coincide with the name of the component and the name of the template file (without any extension)

I hope you find this information useful.
